// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
    async addRecentProject(name: string, path: string): Promise<Result<null, KosmosError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('add_recent_project', { name, path }) };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async getConfig(): Promise<Result<Config, KosmosError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('get_config') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async updateSettings(settings: Settings): Promise<Result<null, KosmosError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('update_settings', { settings }) };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async closeProject(): Promise<Result<null, KosmosError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('close_project') };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async createProject(name: string, path: string): Promise<Result<string, KosmosError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('create_project', { name, path }) };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async openProject(path: string): Promise<Result<string, KosmosError>> {
        try {
            return { status: 'ok', data: await TAURI_INVOKE('open_project', { path }) };
        } catch (e) {
            if (e instanceof Error) throw e;
            else return { status: 'error', error: e as any };
        }
    },
    async greet(name: string): Promise<string> {
        return await TAURI_INVOKE('greet', { name });
    },
};

/** user-defined events **/

/** user-defined constants **/

/** user-defined types **/

export type Config = { settings: Settings; recentProjects: RecentProject[] };
export type KosmosError =
    | 'Io'
    | { Poison: string }
    | 'StripPrefix'
    | 'Database'
    | 'Export'
    | 'Join'
    | 'SerdeJson'
    | 'Tauri'
    | 'Zip'
    | { Bundle: string }
    | 'InvalidFileFormat'
    | 'InvalidPath'
    | { Internal: string };
export type RecentProject = { name: string; path: string; lastOpened: number };
export type Settings = { theme: string; language: string };

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE, Channel as TAURI_CHANNEL } from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
    listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
    once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
    emit: null extends T
        ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
        : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
    return new Proxy(
        {} as unknown as {
            [K in keyof T]: __EventObj__<T[K]> & {
                (handle: __WebviewWindow__): __EventObj__<T[K]>;
            };
        },
        {
            get: (_, event) => {
                const name = mappings[event as keyof T];

                return new Proxy((() => {}) as any, {
                    apply: (_, __, [window]: [__WebviewWindow__]) => ({
                        listen: (arg: any) => window.listen(name, arg),
                        once: (arg: any) => window.once(name, arg),
                        emit: (arg: any) => window.emit(name, arg),
                    }),
                    get: (_, command: keyof __EventObj__<any>) => {
                        switch (command) {
                            case 'listen':
                                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
                            case 'once':
                                return (arg: any) => TAURI_API_EVENT.once(name, arg);
                            case 'emit':
                                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
                        }
                    },
                });
            },
        },
    );
}
